# For details of the below fields, please refer CUSTOMISE.md
PROJECT_NAME: cataract_bot_hierarchy
CHAT_APPLICATION: whatsapp
API_ACTIVATED: true
USERS : ['Student']
EXPERTS:
  Teacher: 'academic'
ESCALATION:
  Teacher: 
    name: 'Senior Teacher'
    whatsapp_id: '919876543210'
USER_PROMPT : 'You are a cataract bot. Your purpose is to help patients with any queries that they might have.'

RECREATE_EMBEDDINGS: false
SHOW_CITATIONS: true
SEND_POLL: false
SEND_CONSENSUS_POLL: true
SUGGEST_NEXT_QUESTIONS: true
MAX_CONVERSATION_LENGTH: 5
GLOB_SUFFIX: '*.txt'

WELCOME_MESSAGES:
  USERS:
    - 'Hi! I am a cataract bot. I can help you with any queries that you have regarding your cataract surgeries.'
  EXPERTS:
    - 'Hi! I am a cataract bot. Thank you for volunteering to help patients with their science queries.'
SUGGESTION_QUESTIONS:
  - 'What topics can you help me with?'
  - 'What is photosynthesis?'
  - 'What is the difference between a plant cell and an animal cell?'

COSMOS_DB_NAME: cataract_hierarchy
COSMOS_DB_COLLECTION: conversation_science_bot
COSMOS_LONGTERM_COLLECTION: science-bot_users
COSMOS_LOGGING_COLLECTION: logs_science_bot
AZURE_BLOB_CONTAINER_NAME: swaasthya-bot-audio-storage

#NEW_DB
COSMOS_USER_COLLECTION: users
COSMOS_RELATIONS_COLLECTION: relations
COSMOS_USER_CONV_COLLECTION: user_conversations
COSMOS_BOT_CONV_COLLECTION: bot_conversations
COSMOS_EXPERT_CONV_COLLECTION: expert_conversations

SPREADSHEET_ID: abcd
SHEET_LINK: https://docs.google.com/spreadsheets/d/abcd/edit?usp=sharing
EMAIL_ID: abcd@gmail.com
EMAIL_PASS: abcd
EMAIL_LIST: ["test@microsoft.com"]